"use client";
export const data = [
  {
    id: 1,
    title: "Frontend Developer",
    datePosted: "2024-11-25",
    companyName: "TechWave Solutions",
    location: "San Francisco, CA",
    salary: "$85,000 - $100,000",
    action: "Apply Now",
  },
  {
    id: 2,
    title: "Backend Engineer",
    datePosted: "2024-11-20",
    companyName: "Innovatech Corp",
    location: "Austin, TX",
    salary: "$95,000 - $110,000",
    action: "Apply Now",
  },
  {
    id: 3,
    title: "Data Analyst",
    datePosted: "2024-11-18",
    companyName: "DataWise Analytics",
    location: "New York, NY",
    salary: "$70,000 - $85,000",
    action: "Apply Now",
  },
  {
    id: 4,
    title: "UI/UX Designer",
    datePosted: "2024-11-22",
    companyName: "Creative Minds Studio",
    location: "Los Angeles, CA",
    salary: "$80,000 - $95,000",
    action: "Apply Now",
  },
  {
    id: 5,
    title: "Full Stack Developer",
    datePosted: "2024-11-15",
    companyName: "CodeSmith Ventures",
    location: "Seattle, WA",
    salary: "$100,000 - $120,000",
    action: "Apply Now",
  },
  {
    id: 1,
    title: "Frontend Developer",
    datePosted: "2024-11-25",
    companyName: "TechWave Solutions",
    location: "San Francisco, CA",
    salary: "$85,000 - $100,000",
    action: "Apply Now",
  },
  {
    id: 2,
    title: "Backend Engineer",
    datePosted: "2024-11-20",
    companyName: "Innovatech Corp",
    location: "Austin, TX",
    salary: "$95,000 - $110,000",
    action: "Apply Now",
  },
  {
    id: 3,
    title: "Data Analyst",
    datePosted: "2024-11-18",
    companyName: "DataWise Analytics",
    location: "New York, NY",
    salary: "$70,000 - $85,000",
    action: "Apply Now",
  },
  {
    id: 4,
    title: "UI/UX Designer",
    datePosted: "2024-11-22",
    companyName: "Creative Minds Studio",
    location: "Los Angeles, CA",
    salary: "$80,000 - $95,000",
    action: "Apply Now",
  },
  {
    id: 5,
    title: "Full Stack Developer",
    datePosted: "2024-11-15",
    companyName: "CodeSmith Ventures",
    location: "Seattle, WA",
    salary: "$100,000 - $120,000",
    action: "Apply Now",
  },
];

export const userData = [
  {
    id: 1,
    name: "David Elen",
    email: "david1122@gmail.com",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    email: "sarah.johnson@mail.com",
  },
  {
    id: 3,
    name: "Michael Brown",
    email: "michael.brown99@gmail.com",
  },
  {
    id: 4,
    name: "Emma Wilson",
    email: "emmawilson45@yahoo.com",
  },
  {
    id: 5,
    name: "James Smith",
    email: "james.smith22@outlook.com",
  },
  {
    id: 6,
    name: "Olivia Davis",
    email: "oliviadavis123@gmail.com",
  },
];

export const cvCreatorsData = [
  {
    id: 1,
    templateName: "Modern Professional",
    userEmail: "john.doe@example.com",
  },
  {
    id: 2,
    templateName: "Classic Elegant",
    userEmail: "jane.smith@example.com",
  },
  {
    id: 3,
    templateName: "Creative Designer",
    userEmail: "michael.brown@example.com",
  },
  {
    id: 4,
    templateName: "Simple Minimal",
    userEmail: "emma.wilson@example.com",
  },
  {
    id: 5,
    templateName: "Corporate Executive",
    userEmail: "olivia.davis@example.com",
  },
  {
    id: 6,
    templateName: "Modern Gradient",
    userEmail: "william.jones@example.com",
  },
  {
    id: 7,
    templateName: "Bold Statement",
    userEmail: "sophia.jackson@example.com",
  },
  {
    id: 8,
    templateName: "Traditional CV",
    userEmail: "liam.anderson@example.com",
  },
];

export const cvMatchersData = [
  {
    id: 1,
    jobTitle: "Software Engineer",
    userEmail: "john.doe@example.com",
  },
  {
    id: 2,
    jobTitle: "Graphic Designer",
    userEmail: "jane.smith@example.com",
  },
  {
    id: 3,
    jobTitle: "Data Analyst",
    userEmail: "michael.brown@example.com",
  },
  {
    id: 4,
    jobTitle: "Marketing Manager",
    userEmail: "emma.wilson@example.com",
  },
  {
    id: 5,
    jobTitle: "Product Manager",
    userEmail: "olivia.davis@example.com",
  },
  {
    id: 6,
    jobTitle: "UX Designer",
    userEmail: "william.jones@example.com",
  },
  {
    id: 7,
    jobTitle: "Cybersecurity Analyst",
    userEmail: "sophia.jackson@example.com",
  },
  {
    id: 8,
    jobTitle: "HR Specialist",
    userEmail: "liam.anderson@example.com",
  },
];

// For detail page
export const data1 = [
  {
    id: 1,
    title: "Frontend Developer",
    companyName: "Tech Solutions Ltd",
    location: "San Francisco, CA",
    country: "USA",
    salary: "$120,000 - $150,000",
    minAnnualSalary: 120000,
    maxAnnualSalary: 150000,
    salaryCurrency: "USD",
    industry: "Information Technology",
    employment_statuses: ["Full-time", "Remote"],
    description:
      "We are looking for a Frontend Developer with strong experience in building scalable frontend applications.",
    jobPostDate: "2024-06-01",
    applyUrl: "https://techsolutions.com/apply/123",
    finalUrl: "https://techsolutions.com/jobs/123",
    sourceUrl: "https://jobboard.com/listing/123",
    stateCode: "CA",
    remote: true,
    hybrid: false,
    seniority: "Senior",
    companyLogoLink: "https://techsolutions.com/logo.png",
    companyUrl: "https://techsolutions.com",
    numberOfJobs: 1,
    foundedYear: 2015,
  },
  {
    id: 2,
    title: "Junior Backend Engineer",
    companyName: "Code Innovators",
    location: "Austin, TX",
    country: "USA",
    salary: "$80,000 - $100,000",
    minAnnualSalary: 80000,
    maxAnnualSalary: 100000,
    salaryCurrency: "USD",
    industry: "Software Development",
    employment_statuses: ["Full-time", "Hybrid"],
    description:
      "A backend engineer role focusing on Node.js and API development.",
    jobPostDate: "2024-06-10",
    applyUrl: "https://codeinnovators.com/apply/456",
    finalUrl: "https://codeinnovators.com/jobs/456",
    sourceUrl: "https://jobboard.com/listing/456",
    stateCode: "TX",
    remote: false,
    hybrid: true,
    seniority: "Junior",
    companyLogoLink: "https://codeinnovators.com/logo.png",
    companyUrl: "https://codeinnovators.com",
    numberOfJobs: 2,
    foundedYear: 2018,
  },
];
